# Generated by Django 5.0.6 on 2024-06-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_blog_category_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('world', 'World'), ('india', 'India'), ('technology', 'Technology'), ('design', 'Design'), ('culture', 'Culture'), ('buisness', 'Buisness'), ('polotics', 'Polotics'), ('opinion', 'Opinion'), ('health', 'Health'), ('style', 'Ttyle'), ('travel', 'Travel')], max_length=100),
        ),
    ]
